/**
 * PhishGuard Grok AI Explainability Service (Phase 7)
 * Consumes verified structured evidence from the Risk Engine and produces
 * human-readable, grounded security explanations and safe recommendations.
 * 
 * IMPORTANT ARCHITECTURAL CONSTRAINTS:
 * 1. Grok NEVER determines or alters the risk score, risk level, or threat category.
 * 2. Risk Engine remains the sole authoritative source of truth.
 * 3. Grok explains ONLY verified signals present in the supplied evidence.
 * 4. API keys and sensitive credentials are never leaked, logged, or returned.
 */

const GROK_DEFAULT_API_URL = 'https://api.x.ai/v1/chat/completions';
const GROK_DEFAULT_MODEL = 'grok-2-latest';
const GROK_DEFAULT_TIMEOUT_MS = 10000;

const GROK_SYSTEM_INSTRUCTION = `You are PhishGuard's security explanation assistant.

Your job is to explain verified security findings generated by PhishGuard's deterministic analysis pipeline.

The supplied risk score, risk level, threat category, and evidence are authoritative.

Do NOT calculate a new risk score.
Do NOT override the supplied risk score.
Do NOT invent evidence.
Do NOT claim that a URL is malicious unless the supplied evidence supports that conclusion.
Do NOT claim that a website was visited unless the supplied evidence explicitly states that it was verified.
Do NOT tell the user to open or interact with a suspicious URL.

Explain:
1. Why the input was flagged.
2. The most important detected indicators.
3. The likely attack intent based only on the evidence.
4. Safe actions the user should take.

Use concise, clear language for non-technical users.
You must respond with valid JSON only matching the schema:
{
  "title": "Concise summary title",
  "explanation": "Clear plain-language explanation of findings",
  "attackIntent": "Inferred objective based only on evidence (e.g. Credential theft, Financial extortion, Benign, Unknown)",
  "keyFindings": ["Finding 1", "Finding 2", ...],
  "recommendedActions": ["Safe action 1", "Safe action 2", ...],
  "disclaimer": "This explanation is based on the security evidence detected by PhishGuard."
}`;

/**
 * Filter and sanitize Risk Engine output so only structured evidence is passed to AI
 * Never include sensitive raw inputs, credentials, tokens, or internal secrets.
 * @param {object} riskResult
 * @returns {object} Sanitized evidence payload
 */
function sanitizeEvidenceForGrok(riskResult) {
  if (!riskResult || typeof riskResult !== 'object') {
    return {
      riskScore: 0,
      riskLevel: 'UNKNOWN',
      threatCategory: 'unknown',
      scoreBreakdown: { url: 0, message: 0, redirect: 0, ml: 0 },
      evidence: []
    };
  }

  // Handle case where riskResult is wrapped inside a 'risk' or 'analysis' key
  const target = riskResult.risk ? riskResult.risk : riskResult;

  const sanitized = {
    riskScore: typeof target.riskScore === 'number' ? target.riskScore : 0,
    riskLevel: target.riskLevel || 'UNKNOWN',
    threatCategory: target.threatCategory || 'unknown',
    confidence: target.confidence || 'low',
    scoreBreakdown: target.scoreBreakdown || { url: 0, message: 0, redirect: 0, ml: 0 },
    evidence: []
  };

  if (target.ml && typeof target.ml === 'object') {
    sanitized.ml = {
      prediction: target.ml.prediction || null,
      probability: typeof target.ml.probability === 'number' ? target.ml.probability : null
    };
  }

  if (Array.isArray(target.evidence)) {
    sanitized.evidence = target.evidence.map(item => ({
      signal: item.signal || 'unknown_signal',
      category: item.category || 'general',
      points: typeof item.points === 'number' ? item.points : 0,
      reason: item.reason || ''
    }));
  }

  return sanitized;
}

/**
 * Validate that the parsed Grok JSON matches the required explanation schema
 * @param {any} data
 * @returns {boolean}
 */
function validateExplanationSchema(data) {
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    return false;
  }

  const isNonEmptyString = val => typeof val === 'string' && val.trim().length > 0;
  const isStringArray = arr => Array.isArray(arr) && arr.length > 0 && arr.every(isNonEmptyString);

  return (
    isNonEmptyString(data.title) &&
    isNonEmptyString(data.explanation) &&
    isNonEmptyString(data.attackIntent) &&
    isStringArray(data.keyFindings) &&
    isStringArray(data.recommendedActions) &&
    isNonEmptyString(data.disclaimer)
  );
}

/**
 * Generate an explainable, human-readable security assessment from Risk Engine output using Grok
 * 
 * @param {object} riskResult - Output from Risk Engine
 * @param {object} [options] - Optional overrides for testing and configuration
 * @param {string} [options.apiKey] - Explicit API key override (for testing)
 * @param {string} [options.apiUrl] - API URL override
 * @param {string} [options.model] - Model name override
 * @param {number} [options.timeoutMs] - Request timeout in milliseconds
 * @param {Function} [options.fetchFn] - Custom fetch function (for unit testing/mocking)
 * @returns {Promise<{ aiStatus: string, explanation: object|null, error?: string }>}
 */
async function generateSecurityExplanation(riskResult, options = {}) {
  // Determine key from options or environment (supports both XAI_API_KEY and GROQ_API_KEY)
  const apiKey = options.apiKey !== undefined
    ? options.apiKey
    : (process.env.XAI_API_KEY || process.env.GROQ_API_KEY);

  // Auto-detect Groq provider if key starts with gsk_ or LLM_PROVIDER is groq
  const isGroq = (apiKey && apiKey.startsWith('gsk_')) || process.env.LLM_PROVIDER === 'groq';

  const defaultApiUrl = isGroq
    ? 'https://api.groq.com/openai/v1/chat/completions'
    : GROK_DEFAULT_API_URL;
  const defaultModel = isGroq
    ? (process.env.GROQ_MODEL || 'groq/compound')
    : GROK_DEFAULT_MODEL;

  const apiUrl = options.apiUrl || process.env.XAI_API_URL || process.env.GROQ_API_URL || defaultApiUrl;
  const model = options.model || process.env.GROK_MODEL || defaultModel;
  const timeoutMs = options.timeoutMs || parseInt(process.env.GROK_TIMEOUT_MS || `${GROK_DEFAULT_TIMEOUT_MS}`, 10);
  const fetchFn = options.fetchFn || global.fetch;

  // 1. Check API Key configuration
  if (!apiKey || typeof apiKey !== 'string' || apiKey.trim().length === 0) {
    return {
      aiStatus: 'unavailable',
      explanation: null,
      error: 'XAI_API_KEY is not configured'
    };
  }

  // 2. Extract sanitized evidence
  const sanitizedEvidence = sanitizeEvidenceForGrok(riskResult);

  // 3. Build prompts
  const userPrompt = `Verified Risk Engine Findings:
${JSON.stringify(sanitizedEvidence, null, 2)}

Provide a plain-language explanation and recommended actions based strictly on this evidence.`;

  const requestBody = {
    model: model,
    messages: [
      { role: 'system', content: GROK_SYSTEM_INSTRUCTION },
      { role: 'user', content: userPrompt }
    ],
    temperature: 0.1,
    response_format: { type: 'json_object' }
  };

  // 4. Execute API request with timeout handling
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const response = await fetchFn(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify(requestBody),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    // Handle HTTP error statuses
    if (!response.ok) {
      const status = response.status;
      let errorBody = '';
      try {
        errorBody = await response.text();
      } catch (_) {}

      if (status === 401 || status === 403) {
        return {
          aiStatus: 'unavailable',
          explanation: null,
          error: `xAI API authentication failed (HTTP ${status})`
        };
      }

      if (status === 429) {
        return {
          aiStatus: 'unavailable',
          explanation: null,
          error: 'xAI API rate limit exceeded (HTTP 429)'
        };
      }

      return {
        aiStatus: 'unavailable',
        explanation: null,
        error: `xAI API returned HTTP ${status}: ${errorBody.slice(0, 120)}`
      };
    }

    // 5. Parse response content
    const responseData = await response.json();
    const rawContent = responseData?.choices?.[0]?.message?.content;

    if (!rawContent || typeof rawContent !== 'string') {
      return {
        aiStatus: 'invalid_response',
        explanation: null,
        error: 'xAI API returned empty or missing message content'
      };
    }

    // Parse JSON output from model
    let parsedExplanation;
    try {
      // Remove any surrounding markdown code block if present
      const cleaned = rawContent.replace(/^```json\s*/i, '').replace(/\s*```$/, '').trim();
      parsedExplanation = JSON.parse(cleaned);
    } catch (parseErr) {
      return {
        aiStatus: 'invalid_response',
        explanation: null,
        error: `Failed to parse Grok JSON: ${parseErr.message}`
      };
    }

    // 6. Validate parsed schema
    if (!validateExplanationSchema(parsedExplanation)) {
      return {
        aiStatus: 'invalid_response',
        explanation: null,
        error: 'Grok response does not satisfy required schema structure'
      };
    }

    // 7. Ensure standard disclaimer is preserved
    if (!parsedExplanation.disclaimer) {
      parsedExplanation.disclaimer = 'This explanation is based on the security evidence detected by PhishGuard.';
    }

    return {
      aiStatus: 'success',
      explanation: parsedExplanation
    };

  } catch (err) {
    clearTimeout(timeoutId);

    if (err.name === 'AbortError') {
      return {
        aiStatus: 'unavailable',
        explanation: null,
        error: `Grok API request timed out after ${timeoutMs}ms`
      };
    }

    return {
      aiStatus: 'unavailable',
      explanation: null,
      error: `Network error connecting to Grok API: ${err.message}`
    };
  }
}

module.exports = {
  GROK_DEFAULT_API_URL,
  GROK_DEFAULT_MODEL,
  GROK_DEFAULT_TIMEOUT_MS,
  GROK_SYSTEM_INSTRUCTION,
  sanitizeEvidenceForGrok,
  validateExplanationSchema,
  generateSecurityExplanation
};
